const SET_ACTIVE_USER = "SET_ACTIVE_USER",
  SET_NEW_EMPLOYEE_DATA = "SET_NEW_EMPLOYEE_DATA",
  LOG_IN = "LOG_IN",
  LOG_OUT = "LOG_OUT",
  SET_COST = "SET_COST";

export { SET_ACTIVE_USER, SET_NEW_EMPLOYEE_DATA, LOG_IN, LOG_OUT, SET_COST };
