const SET_ACTIVE_USER = "SET_ACTIVE_USER",
  SET_NEW_EMPLOYEE_DATA = "SET_NEW_EMPLOYEE_DATA",
  LOG_IN = "LOG_IN",
  LOG_OUT = "LOG_OUT";

export { SET_ACTIVE_USER, SET_NEW_EMPLOYEE_DATA, LOG_IN, LOG_OUT };
